[workspace]
authors = ["Thomas Li <ktliac@connect.ust.hk>"]
channels = ["conda-forge"]
name = "TwoStreamNetwork"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
start = "uvicorn app:app --root-path '/sign2text'"

[dependencies]
python = "3.10.*"
pytorch-gpu = "==1.13.1"
torchvision = "==0.14.1"
fastapi = ">=0.115.12,<0.116"
ffmpeg-python = ">=0.2.0,<0.3"
redis-py = ">=6.2.0,<7"
tensorflow-gpu = ">=2.11.1,<3"
wandb = ">=0.20.1,<0.21"
transformers = ">=4.37.2,<4.38"
sentencepiece = ">=0.1.97,<0.2"
ffmpeg = ">=6.1.0,<7"

[system-requirements]
libc = { family = "glibc", version = "2.17" }
cuda = "11.7"

[activation.env]
LD_LIBRARY_PATH = "${CONDA_PREFIX}/lib:${LD_LIBRARY_PATH}"
