services:
  valkey:
    image: valkey/valkey:latest
    restart: always
    ports:
      - "6379:6379"
  # cloudflared:
  #   image: "cloudflare/cloudflared:latest"
  #   command: tunnel run
  #   network_mode: bridge
  #   env_file:
  #     - .env
